#!/bin/bash
# Sync quickshell colors to Mako and Vicinae
# Called automatically by shell.qml whenever theme/colors change.
# Uses a lockfile + atomic writes to prevent corruption on rapid calls.

# Arguments:
# $1 = background hex     $7  = yellow hex
# $2 = surface hex        $8  = blue hex
# $3 = foreground hex     $9  = cyan hex
# $4 = accent hex         $10 = magenta hex
# $5 = red hex            $11 = textMuted hex
# $6 = green hex          $12 = themeName

BG="$1";   SUR="$2";  FG="$3";   ACC="$4"
RED="$5";  GRN="$6";  YEL="$7";  BLU="$8"
CYN="$9";  MAG="${10}"; MUT="${11}"; THEME="${12}"

# Fallback defaults if args are missing
[ -z "$BG"  ] && BG="#0d0f18";    [ -z "$SUR" ] && SUR="#1e1e2e"
[ -z "$FG"  ] && FG="#c0caf5";    [ -z "$ACC" ] && ACC="#7aa2f7"
[ -z "$RED" ] && RED="#f7768e";   [ -z "$GRN" ] && GRN="#9ece6a"
[ -z "$YEL" ] && YEL="#e0af68";   [ -z "$BLU" ] && BLU="#7aa2f7"
[ -z "$CYN" ] && CYN="#7dcfff";   [ -z "$MAG" ] && MAG="#bb9af7"
[ -z "$MUT" ] && MUT="#6D8895"

# Prevent parallel runs stomping on each other
LOCK="/tmp/qs-theme-sync.lock"
exec 9>"$LOCK"
flock -x 9

# Strip '#' for mako background-color opacity suffix
BG_HEX="${BG#\#}"

# ──────────────────────────────────────────────────────────────────────────
# 1. Update Mako Configuration (atomic write via temp file)
# ──────────────────────────────────────────────────────────────────────────
MAKO_CONF="$HOME/.config/mako/config"
MAKO_TMP="$(mktemp)"

cat <<EOF > "$MAKO_TMP"
# Take a look at the mako manpage with the command:
#   man 5 mako
# To view all configuration options.
# Automatically generated by quickshell theme sync — do not hand-edit.

font=JetBrains Mono Nerd Font 11
format=<b>%a ⏵</b> %s\n%b
sort=-time
layer=overlay
anchor=top-center
width=500
height=50
margin=5
padding=8,12,12
border-size=2
icons=1
max-icon-size=20
default-timeout=5000
ignore-timeout=1

# System Colors (synced from theme: $THEME)
background-color=#${BG_HEX}dd
text-color=$FG
border-color=$ACC
border-radius=12

[urgency=normal]
border-color=$ACC

[urgency=high]
border-color=$RED
default-timeout=0

[app-name=lightcord]
border-color=$MUT

[summary~="log-.*"]
border-color=$SUR
EOF

mv -f "$MAKO_TMP" "$MAKO_CONF"
makoctl reload 2>/dev/null

# ──────────────────────────────────────────────────────────────────────────
# 2. Update Vicinae Theme (atomic write via temp file)
# ──────────────────────────────────────────────────────────────────────────
VICINAE_THEME_DIR="$HOME/.local/share/vicinae/themes"
mkdir -p "$VICINAE_THEME_DIR"
VICINAE_TMP="$(mktemp)"

cat <<EOF > "$VICINAE_TMP"
# Automatically generated by quickshell theme sync — do not hand-edit.
[meta]
name = "Custom theme"
description = "Synchronized with quickshell theme: $THEME"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent             = "$ACC"
accent_foreground  = "$BG"
background         = "$BG"
foreground         = "$FG"
secondary_background = "$SUR"
border             = "$SUR"

[colors.main_window]
border = "$SUR"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "$SUR"

[colors.accents]
blue    = "$BLU"
green   = "$GRN"
magenta = "$MAG"
orange  = "$YEL"
red     = "$RED"
yellow  = "$YEL"
cyan    = "$CYN"
purple  = "$MAG"

[colors.shortcut]
border = "$SUR"
EOF

mv -f "$VICINAE_TMP" "$VICINAE_THEME_DIR/custom.toml"
vicinae theme set custom 2>/dev/null

# ──────────────────────────────────────────────────────────────────────────
# 3. Update Neovim Theme & Live Reload Active Neovim Instances
# ──────────────────────────────────────────────────────────────────────────
NVIM_THEME_DIR="$HOME/dotfiles/config/nvim/lua/generated"
mkdir -p "$NVIM_THEME_DIR"
NVIM_TMP="$(mktemp)"

cat <<EOF > "$NVIM_TMP"
-- Automatically generated by quickshell theme sync for theme: $THEME
return {
    base00 = "$BG",
    base01 = "$BG",
    base02 = "$SUR",
    base03 = "$GRN",
    base04 = "$FG",
    base05 = "$FG",
    base06 = "$YEL",
    base07 = "$FG",
    base08 = "$RED",
    base09 = "$MAG",
    base0A = "$YEL",
    base0B = "$ACC",
    base0C = "$CYN",
    base0D = "$BLU",
    base0E = "$MAG",
    base0F = "$RED",
}
EOF

mv -f "$NVIM_TMP" "$NVIM_THEME_DIR/theme.lua"

# Live-reload all running Neovim instances over RPC sockets
for socket in /tmp/nvim*/* /run/user/1000/nvim*/*; do
    if [ -S "$socket" ]; then
        nvim --server "$socket" --remote-send "<Cmd>lua require('theme').reload()<CR>" 2>/dev/null &
    fi
done

# ──────────────────────────────────────────────────────────────────────────
# 4. Update KDE Color Scheme & Apply to Plasma / Qt / KDE Apps
# ──────────────────────────────────────────────────────────────────────────
KDE_SCHEME_DIR="$HOME/.local/share/color-schemes"
mkdir -p "$KDE_SCHEME_DIR"

hex_to_rgb() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "$r,$g,$b"
}

BG_RGB=$(hex_to_rgb "$BG")
SUR_RGB=$(hex_to_rgb "$SUR")
FG_RGB=$(hex_to_rgb "$FG")
ACC_RGB=$(hex_to_rgb "$ACC")

# Calculate high-contrast bright inactive text color for file labels
INACT_RGB="220,225,245"

# Select closest dark Tela icon theme matching the accent color or static theme name
ICON_THEME=$(python3 -c "
tela_colors = {
    'Tela-blue-dark': '#5297e0',
    'Tela-green-dark': '#4caf50',
    'Tela-red-dark': '#e53935',
    'Tela-purple-dark': '#9c27b0',
    'Tela-pink-dark': '#e91e63',
    'Tela-orange-dark': '#ff9800',
    'Tela-yellow-dark': '#ffeb3b',
    'Tela-grey-dark': '#607d8b',
    'Tela-black-dark': '#212121',
    'Tela-dracula-dark': '#bd93f9',
    'Tela-nord-dark': '#88c0d0',
    'Tela-manjaro-dark': '#16a085',
}

theme_overrides = {
    'aline': 'Tela-blue-dark',
    'emilia': 'Tela-blue-dark',
    'h4ck3r': 'Tela-green-dark',
    'z0mbi3': 'Tela-black-dark',
    'dracula': 'Tela-dracula-dark',
    'nord': 'Tela-nord-dark'
}

theme = '$THEME'.lower()
if theme in theme_overrides:
    print(theme_overrides[theme])
else:
    acc = '$ACC'.lstrip('#')
    r, g, b = tuple(int(acc[i:i+2], 16) for i in (0, 2, 4))
    best_name = 'Tela-blue-dark'
    best_dist = 9999999
    for name, hex_val in tela_colors.items():
        tr, tg, tb = tuple(int(hex_val.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
        dist = (r - tr)**2 + (g - tg)**2 + (b - tb)**2
        if dist < best_dist:
            best_dist = dist
            best_name = name
    print(best_name)
")

KDE_TMP="$(mktemp)"
cat <<EOF > "$KDE_TMP"
[General]
ColorScheme=FluxDots
Name=FluxDots
accentColor=$ACC_RGB
LastUsedCustomAccentColor=$ACC_RGB

[UiSettings]
ColorScheme=FluxDots

[Icons]
Theme=$ICON_THEME

[KDE]
LookAndFeelPackage=org.kde.breezedark.desktop
contrast=7

[Colors:Window]
BackgroundNormal=$BG_RGB
ForegroundNormal=240,244,255
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[Colors:View]
BackgroundNormal=$BG_RGB
ForegroundNormal=240,244,255
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[Colors:Button]
BackgroundNormal=$SUR_RGB
ForegroundNormal=240,244,255
BackgroundAlternate=$BG_RGB
ForegroundInactive=$INACT_RGB

[Colors:Selection]
BackgroundNormal=$ACC_RGB
ForegroundNormal=255,255,255
BackgroundAlternate=$ACC_RGB
ForegroundInactive=255,255,255

[Colors:Header]
BackgroundNormal=$BG_RGB
ForegroundNormal=240,244,255

[Colors:Tooltip]
BackgroundNormal=$SUR_RGB
ForegroundNormal=240,244,255

[Colors:Complementary]
BackgroundNormal=$BG_RGB
ForegroundNormal=240,244,255
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[WM]
activeBackground=$BG_RGB
activeBlend=$BG_RGB
activeForeground=240,244,255
inactiveBackground=$BG_RGB
inactiveBlend=$BG_RGB
inactiveForeground=$INACT_RGB
EOF

mv -f "$KDE_TMP" "$KDE_SCHEME_DIR/FluxDots.colors"

# Force Plasma's color manager to register FluxDots
kwriteconfig6 --file kdeglobals --group General --key ColorScheme "Dummy" 2>/dev/null
plasma-apply-colorscheme FluxDots 2>/dev/null || true

# Atomic sync FluxDots.colors directly into kdeglobals so all ForegroundNormal/ForegroundInactive keys are preserved
cp -f "$KDE_SCHEME_DIR/FluxDots.colors" "$HOME/.config/kdeglobals"
kwriteconfig6 --file dolphinrc --group UiSettings --key ColorScheme "FluxDots" 2>/dev/null
kwriteconfig6 --file plasmarc --group Theme --key name breeze-dark 2>/dev/null

# Update GTK settings.ini for icon theme sync
[ -f "$HOME/.config/gtk-3.0/settings.ini" ] && sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-3.0/settings.ini" 2>/dev/null || true
[ -f "$HOME/.config/gtk-4.0/settings.ini" ] && sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-4.0/settings.ini" 2>/dev/null || true

# ──────────────────────────────────────────────────────────────────────────
# 5. Update Kvantum Theme (FluxDots) for Wallust & Static Theme Modes
# ──────────────────────────────────────────────────────────────────────────
KVANTUM_DIR="$HOME/.config/Kvantum/FluxDots"
mkdir -p "$KVANTUM_DIR"

cat <<EOF > "$HOME/.config/Kvantum/kvantum.kvconfig"
[General]
theme=FluxDots
EOF

KV_TMP="$(mktemp)"
cat <<EOF > "$KV_TMP"
[General]
author=FluxDots
comment="Dynamic Kvantum theme for Wallust & Quickshell static themes ($THEME)"

[Applications]
Default=FluxDots

[GeneralColors]
window.color=$BG
window.text.color=#F0F4FF
base.color=$SUR
alt.base.color=$SUR
text.color=#F0F4FF
highlight.color=$ACC
highlight.text.color=#FFFFFF
button.color=$SUR
button.text.color=#F0F4FF
tooltip.color=$SUR
tooltip.text.color=#F0F4FF
inactive.window.color=$BG
inactive.text.color=#DCDEF5
EOF

mv -f "$KV_TMP" "$KVANTUM_DIR/FluxDots.kvconfig"



