[meta]
version = 1
name = "custom"
description = "Dynamic Wallust theme for Vicinae"
variant = "dark"

[colors.core]
background = "#322E37"
foreground = "#DBF0FC"
secondary_background = "#56525C"
border = "#889DA9"
accent = "#FF7D5C"

[colors.input]
background = "#56525C"
text = "#DBF0FC"
placeholder = "#889DA9"
border = "#889DA9"

[colors.list]
background = "#322E37"
text = "#DBF0FC"

[colors.accents]
blue = "#FF7D5C"
green = "#B43C5D"
magenta = "#F8C063"
orange = "#2174BD"
purple = "#F8C063"
red = "#362756"
yellow = "#2174BD"
cyan = "#97D3F6"

[colors.list.item.selection]
background = "#FF7D5C"
secondary_background = "#889DA9"
text = "#DBF0FC"

[colors.grid.item]
background = "#56525C"
