[meta]
version = 1
name = "custom"
description = "Dynamic Wallust theme for Vicinae"
variant = "dark"

[colors.core]
background = "#000003"
foreground = "#FCFAF9"
secondary_background = "#000003"
border = "#A9A8A7"
accent = "#96969B"

[colors.input]
background = "#000003"
text = "#FCFAF9"
placeholder = "#A9A8A7"
border = "#A9A8A7"

[colors.list]
background = "#000003"
text = "#FCFAF9"

[colors.accents]
blue = "#96969B"
green = "#30737B"
magenta = "#13C9CC"
orange = "#258EE9"
purple = "#13C9CC"
red = "#41424D"
yellow = "#258EE9"
cyan = "#F6F1EF"

[colors.list.item.selection]
background = "#96969B"
secondary_background = "#A9A8A7"
text = "#FCFAF9"

[colors.grid.item]
background = "#000003"
