// Wallust generated colors for Quickshell
// This file is REGENERATED by ~/.config/quickshell/scripts/wallust-apply.sh
// on every `wallust run <wallpaper>` call. Do not hand-edit the color values;
// edit the wallust templates/*.qml.tmpl instead.
//
// Generated on: 

pragma Singleton
import QtQuick

QtObject {
    readonly property string background: "#070000"
    readonly property string foreground: "#F9F5EF"
    readonly property string color0: "#0E0504"
    readonly property string color1: "#AB6341"
    readonly property string color2: "#AB7987"
    readonly property string color3: "#BF9F8C"
    readonly property string color4: "#9DABA7"
    readonly property string color5: "#D2DFF6"
    readonly property string color6: "#EEE3D1"
    readonly property string color7: "#EEE9E0"
    readonly property string color8: "#A7A39C"
    readonly property string color9: "#AB6341"
    readonly property string color10: "#AB7987"
    readonly property string color11: "#BF9F8C"
    readonly property string color12: "#9DABA7"
    readonly property string color13: "#D2DFF6"
    readonly property string color14: "#EEE3D1"
    readonly property string color15: "#EEE9E0"

    // Convenience aliases so ThemeManager/shell.qml don't need to know
    // which raw color# maps to which semantic role.
    readonly property string accent: color4
    readonly property string surface: color0 !== background ? color0 : (color8 !== background ? color8 : "#1e1e2e")
    readonly property string textMuted: color7

    // Bright colors for icons
    readonly property string brightRed: color9
    readonly property string brightGreen: color10
    readonly property string brightYellow: color11
    readonly property string brightBlue: color12
    readonly property string brightMagenta: color13
    readonly property string brightCyan: color14
    readonly property string brightAccent: color12
}