// Wallust generated colors for Quickshell
// This file is REGENERATED by ~/.config/quickshell/scripts/wallust-apply.sh
// on every `wallust run <wallpaper>` call. Do not hand-edit the color values;
// edit the wallust templates/*.qml.tmpl instead.
//
// Generated on: 

pragma Singleton
import QtQuick

QtObject {
    readonly property string background: "#322E37"
    readonly property string foreground: "#DBF0FC"
    readonly property string color0: "#56525C"
    readonly property string color1: "#362756"
    readonly property string color2: "#B43C5D"
    readonly property string color3: "#2174BD"
    readonly property string color4: "#FF7D5C"
    readonly property string color5: "#F8C063"
    readonly property string color6: "#97D3F6"
    readonly property string color7: "#C2E1F2"
    readonly property string color8: "#889DA9"
    readonly property string color9: "#362756"
    readonly property string color10: "#B43C5D"
    readonly property string color11: "#2174BD"
    readonly property string color12: "#FF7D5C"
    readonly property string color13: "#F8C063"
    readonly property string color14: "#97D3F6"
    readonly property string color15: "#C2E1F2"

    // Convenience aliases so ThemeManager/shell.qml don't need to know
    // which raw color# maps to which semantic role. This is the seam
    // a future "per-theme accent picker" would hook into.
    readonly property string accent: color4
    readonly property color surface: Qt.lighter(background, 1.12)
    readonly property string textMuted: color7

    // Bright colors for icons
    readonly property string brightRed: color9
    readonly property string brightGreen: color10
    readonly property string brightYellow: color11
    readonly property string brightBlue: color12
    readonly property string brightMagenta: color13
    readonly property string brightCyan: color14
    readonly property string brightAccent: color12
}