#!/usr/bin/env python3
"""
btop-smart-theme.py
Generates a dynamic Wallust theme for btop with WCAG AA contrast enforcement.
Updates ~/.config/btop/themes/wallust.theme and ensures btop.conf uses it.
"""

import os
import re
import colorsys

color_script = os.path.expanduser("~/.config/scripts/shared/dynamic-color.sh")
raw_colors = {}
if os.path.isfile(color_script):
    with open(color_script) as f:
        for line in f:
            m = re.match(r'^(\w+)="(#[0-9A-Fa-f]{6})"', line.strip())
            if m:
                raw_colors[m.group(1).upper()] = m.group(2)

def get(key, fallback):
    return raw_colors.get(key.upper(), fallback)

BG  = get("BACKGROUND", "#1e1e2e")
FG  = get("FOREGROUND", "#cdd6f4")
C0  = get("COLOR0",  "#45475a")
C1  = get("COLOR1",  "#f38ba8")
C2  = get("COLOR2",  "#a6e3a1")
C3  = get("COLOR3",  "#f9e2af")
C4  = get("COLOR4",  "#89b4fa")
C5  = get("COLOR5",  "#cba6f7")
C6  = get("COLOR6",  "#89dceb")
C7  = get("COLOR7",  "#bac2de")
C8  = get("COLOR8",  "#585b70")
C9  = get("COLOR9",  "#f38ba8")
C10 = get("COLOR10", "#a6e3a1")
C11 = get("COLOR11", "#f9e2af")
C12 = get("COLOR12", "#89b4fa")

def hex_to_rgb(h):
    s = h.lstrip("#")
    if len(s) != 6: return (0, 0, 0)
    return int(s[0:2],16)/255, int(s[2:4],16)/255, int(s[4:6],16)/255

def luma(h):
    r, g, b = hex_to_rgb(h)
    def lin(c): return c/12.92 if c <= 0.04045 else ((c+0.055)/1.055)**2.4
    return 0.2126*lin(r) + 0.7152*lin(g) + 0.0722*lin(b)

def contrast_ratio(a, b_col):
    la, lb = luma(a)+0.05, luma(b_col)+0.05
    return max(la, lb) / min(la, lb)

def ensure_contrast(hex_col, bg_col, min_ratio=4.5):
    r, g, b = hex_to_rgb(hex_col)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    is_bg_light = luma(bg_col) > 0.50
    curr_col = hex_col
    step = -0.04 if is_bg_light else 0.04
    for _ in range(25):
        if contrast_ratio(curr_col, bg_col) >= min_ratio:
            break
        l = max(0.05, min(0.95, l + step))
        r_new, g_new, b_new = colorsys.hls_to_rgb(h, l, s)
        curr_col = '#{:02X}{:02X}{:02X}'.format(int(r_new*255), int(g_new*255), int(b_new*255))
    return curr_col

# Contrast-checked colors for btop
main_fg   = ensure_contrast(FG, BG, 4.5)
title_fg  = ensure_contrast(C4, BG, 4.5)
hi_fg     = ensure_contrast(C6, BG, 4.5)
inactive  = ensure_contrast(C8 if C8 != BG else C7, BG, 3.2)
graph_txt = ensure_contrast(FG, BG, 4.5)

cpu_box   = ensure_contrast(C4, BG, 4.5)
mem_box   = ensure_contrast(C2, BG, 4.5)
net_box   = ensure_contrast(C3, BG, 4.5)
proc_box  = ensure_contrast(C5, BG, 4.5)
div_line  = ensure_contrast(C0 if C0 != BG else C8, BG, 2.5)

sel_bg    = ensure_contrast(C0 if C0 != BG else C8, BG, 2.0)
sel_fg    = "#ffffff" if contrast_ratio("#ffffff", sel_bg) >= contrast_ratio("#0f172a", sel_bg) else "#0f172a"

# Theme file content
theme_content = f"""# Wallust Dynamic btop theme
# Automatically generated by btop-smart-theme.py

theme[main_bg]=""
theme[main_fg]="{main_fg}"
theme[title]="{title_fg}"
theme[hi_fg]="{hi_fg}"
theme[selected_bg]="{sel_bg}"
theme[selected_fg]="{sel_fg}"
theme[inactive_fg]="{inactive}"
theme[graph_text]="{graph_txt}"

theme[cpu_box]="{cpu_box}"
theme[mem_box]="{mem_box}"
theme[net_box]="{net_box}"
theme[proc_box]="{proc_box}"
theme[div_line]="{div_line}"

theme[temp_start]="{C2}"
theme[temp_mid]="{C3}"
theme[temp_end]="{C1}"

theme[cpu_start]="{C4}"
theme[cpu_mid]="{C6}"
theme[cpu_end]="{C5}"

theme[free_start]="{C2}"
theme[free_mid]="{C10}"
theme[free_end]="{C3}"

theme[cached_start]="{C4}"
theme[cached_mid]="{C12}"
theme[cached_end]="{C6}"

theme[available_start]="{C2}"
theme[available_mid]="{C3}"
theme[available_end]="{C1}"

theme[used_start]="{C1}"
theme[used_mid]="{C5}"
theme[used_end]="{C4}"

theme[download_start]="{C2}"
theme[download_mid]="{C6}"
theme[download_end]="{C4}"

theme[upload_start]="{C5}"
theme[upload_mid]="{C4}"
theme[upload_end]="{C6}"

theme[process_start]="{C4}"
theme[process_mid]="{C6}"
theme[process_end]="{C5}"
"""

theme_path = os.path.expanduser("~/.config/btop/themes/wallust.theme")
os.makedirs(os.path.dirname(theme_path), exist_ok=True)
with open(theme_path, "w") as f:
    f.write(theme_content)

# Update btop.conf to point to wallust.theme
btop_conf = os.path.expanduser("~/.config/btop/btop.conf")
if os.path.isfile(btop_conf):
    with open(btop_conf, "r") as f:
        conf_txt = f.read()
    
    new_conf = re.sub(r'^color_theme\s*=.*', 'color_theme = "wallust"', conf_txt, flags=re.M)
    new_conf = re.sub(r'^theme_background\s*=.*', 'theme_background = False', new_conf, flags=re.M)
    with open(btop_conf, "w") as f:
        f.write(new_conf)

print(f"btop theme regenerated at {theme_path} (color_theme = 'wallust')")
