// Wallust generated colors for Quickshell
// This file is REGENERATED by ~/.config/quickshell/scripts/wallust-apply.sh
// on every `wallust run <wallpaper>` call. Do not hand-edit the color values;
// edit the wallust templates/*.qml.tmpl instead.
//
// Generated on: 

pragma Singleton
import QtQuick

QtObject {
    readonly property string background: "#2C2725"
    readonly property string foreground: "#ECFCAF"
    readonly property string color0: "#524C4A"
    readonly property string color1: "#387853"
    readonly property string color2: "#917458"
    readonly property string color3: "#79BEE5"
    readonly property string color4: "#79CAA0"
    readonly property string color5: "#F9DDB9"
    readonly property string color6: "#C9F51B"
    readonly property string color7: "#DBF284"
    readonly property string color8: "#9AA95D"
    readonly property string color9: "#387853"
    readonly property string color10: "#917458"
    readonly property string color11: "#79BEE5"
    readonly property string color12: "#79CAA0"
    readonly property string color13: "#F9DDB9"
    readonly property string color14: "#C9F51B"
    readonly property string color15: "#DBF284"

    // Convenience aliases so ThemeManager/shell.qml don't need to know
    // which raw color# maps to which semantic role. This is the seam
    // a future "per-theme accent picker" would hook into.
    readonly property string accent: color4
    readonly property string surface: color0
    readonly property string textMuted: color8
}