// Wallust generated colors for Quickshell
// This file is REGENERATED by ~/.config/quickshell/scripts/wallust-apply.sh
// on every `wallust run <wallpaper>` call. Do not hand-edit the color values;
// edit the wallust templates/*.qml.tmpl instead.
//
// Generated on: 

pragma Singleton
import QtQuick

QtObject {
    readonly property string background: "#212425"
    readonly property string foreground: "#E8F5F0"
    readonly property string color0: "#474A4B"
    readonly property string color1: "#18252D"
    readonly property string color2: "#2B5544"
    readonly property string color3: "#6A6462"
    readonly property string color4: "#6E947A"
    readonly property string color5: "#B1A187"
    readonly property string color6: "#BEE2D4"
    readonly property string color7: "#D6E8E1"
    readonly property string color8: "#96A29E"
    readonly property string color9: "#18252D"
    readonly property string color10: "#2B5544"
    readonly property string color11: "#6A6462"
    readonly property string color12: "#6E947A"
    readonly property string color13: "#B1A187"
    readonly property string color14: "#BEE2D4"
    readonly property string color15: "#D6E8E1"

    // Convenience aliases so ThemeManager/shell.qml don't need to know
    // which raw color# maps to which semantic role. This is the seam
    // a future "per-theme accent picker" would hook into.
    readonly property string accent: color4
    readonly property string surface: color0
    readonly property string textMuted: color8
}