// Wallust generated colors for Quickshell
// This file is REGENERATED by ~/.config/quickshell/scripts/wallust-apply.sh
// on every `wallust run <wallpaper>` call. Do not hand-edit the color values;
// edit the wallust templates/*.qml.tmpl instead.
//
// Generated on: 

pragma Singleton
import QtQuick

QtObject {
    readonly property string background: "#202224"
    readonly property string foreground: "#F4EADB"
    readonly property string color0: "#46484A"
    readonly property string color1: "#15242B"
    readonly property string color2: "#454E51"
    readonly property string color3: "#604E47"
    readonly property string color4: "#717070"
    readonly property string color5: "#9E927D"
    readonly property string color6: "#E0C298"
    readonly property string color7: "#E7D8C3"
    readonly property string color8: "#A29788"
    readonly property string color9: "#15242B"
    readonly property string color10: "#454E51"
    readonly property string color11: "#604E47"
    readonly property string color12: "#717070"
    readonly property string color13: "#9E927D"
    readonly property string color14: "#E0C298"
    readonly property string color15: "#E7D8C3"

    // Convenience aliases so ThemeManager/shell.qml don't need to know
    // which raw color# maps to which semantic role. This is the seam
    // a future "per-theme accent picker" would hook into.
    readonly property string accent: color4
    readonly property string surface: color0
    readonly property string textMuted: color8
}