backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.config/hypr/themes/wallust.conf'
kitty.template = 'kitty.conf'
kitty.target = '~/.config/kitty/wallust.conf'
dynamic-color.template = 'dynamic-color.sh'
dynamic-color.target = '~/.config/scripts/shared/dynamic-color.sh'
mako.template = 'colors-mako'
mako.target = '~/.config/mako/config'

firefox.template = 'colors-firefox.css'
firefox.target = '~/.config/firefox/colors-firefox.css'
userFirefox.template = 'userColors.css'
userFirefox.target = '~/.mozilla/firefox/d2hzuyk2.default-release/chrome/userColor.css'

starship.template = 'starship.toml'
starship.target = '~/.config/starship.toml'
quickshell.template = 'quickshell-colors.qml'
quickshell.target = '~/.config/quickshell/wallust-colors.qml'
nvim.template = 'nvim-theme.lua'
nvim.target = '~/dotfiles/config/nvim/lua/generated/theme.lua'
obs.template = 'obs.ovt'
obs.target = '~/.config/obs-studio/themes/Wallust.ovt'
gtk3.template = 'gtk.css'
gtk3.target = '~/.config/gtk-3.0/gtk.css'
gtk4.template = 'gtk.css'
gtk4.target = '~/.config/gtk-4.0/gtk.css'

openrgb.template = 'openrgb.txt'
openrgb.target = '~/.config/openrgb.txt'
