$terminal = kitty
$fileManager = dolphin
$menu = vicinae open

# Main Hyprland Config (modular)
source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/animations.conf
source = ~/.config/hypr/config/keybinds.conf
source = ~/.config/hypr/config/appearance.conf
source = ~/.config/hypr/config/windowrules.conf
source = ~/.config/hypr/config/misc.conf

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
