$wallpaper = /home/tarzo/wallpaper/beautiful-shot-snowy-mountain-sunset.jpg
$background = rgba(202224FF)
$foreground = rgba(F4EADBFF)
$color0 = rgba(46484AFF)
$color1 = rgba(15242BFF)
$color2 = rgba(454E51FF)
$color3 = rgba(604E47FF)
$color4 = rgba(717070FF)
$color5 = rgba(9E927DFF)
$color6 = rgba(E0C298FF)
$color7 = rgba(E7D8C3FF)
$color8 = rgba(A29788FF)
$color9 = rgba(15242BFF)
$color10 = rgba(454E51FF)
$color11 = rgba(604E47FF)
$color12 = rgba(717070FF)
$color13 = rgba(9E927DFF)
$color14 = rgba(E0C298FF)
$color15 = rgba(E7D8C3FF)
