source = ~/.config/hypr/themes/wallust.conf

general {
    gaps_in = 2
    gaps_out = 2

    border_size = 1

    col.active_border = $color4
    col.inactive_border = $color0

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 4

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}
