exec-once = awww
exec-once = waypaper --restore
exec-once = vicinae server
exec-once = ~/.config/quickshell/scripts/startup.sh
exec-once = mako
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
