# Hyprland 0.56.0 Window Rules

windowrule = float = true, match:class = ^(org\.pulseaudio\.pavucontrol)$
windowrule = float = true, match:initial_class = ^(org\.pulseaudio\.pavucontrol)$
windowrule = float = true, match:title = ^(Volume Control)$
windowrule = float = true, match:initial_title = ^(Volume Control)$
windowrule = size = 680 480, match:initial_class = ^(org\.pulseaudio\.pavucontrol)$
windowrule = center = true, match:initial_class = ^(org\.pulseaudio\.pavucontrol)$

windowrule = float = true, match:class = ^(nm-connection-editor)$
windowrule = float = true, match:initial_class = ^(nm-connection-editor)$
windowrule = float = true, match:title = ^(Network Connections)$
windowrule = size = 620 480, match:initial_class = ^(nm-connection-editor)$
windowrule = center = true, match:initial_class = ^(nm-connection-editor)$

windowrule = float = true, match:class = ^(systemsettings)$
windowrule = float = true, match:class = ^(kcmshell6)$
windowrule = float = true, match:class = ^(org\.kde\.plasmawindowed)$
windowrule = size = 450 550, match:class = ^(org\.kde\.plasmawindowed)$
windowrule = center = true, match:class = ^(org\.kde\.plasmawindowed)$
