# Ignore maximize requests from apps
windowrule = match:class .*, suppress_event = maximize

# Fix XWayland unmanaged drag windows
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, no_focus = true
