$wallpaper = /home/tarzo/wallpaper/ozjib9yot4ke1.jpeg
$background = rgba(212425FF)
$foreground = rgba(E8F5F0FF)
$color0 = rgba(474A4BFF)
$color1 = rgba(18252DFF)
$color2 = rgba(2B5544FF)
$color3 = rgba(6A6462FF)
$color4 = rgba(6E947AFF)
$color5 = rgba(B1A187FF)
$color6 = rgba(BEE2D4FF)
$color7 = rgba(D6E8E1FF)
$color8 = rgba(96A29EFF)
$color9 = rgba(18252DFF)
$color10 = rgba(2B5544FF)
$color11 = rgba(6A6462FF)
$color12 = rgba(6E947AFF)
$color13 = rgba(B1A187FF)
$color14 = rgba(BEE2D4FF)
$color15 = rgba(D6E8E1FF)
