-- Environment Variables (end4 architecture)
set_env("XCURSOR_SIZE", "24")
set_env("HYPRCURSOR_SIZE", "24")
set_env("GDK_BACKEND", "wayland,x11,*")
set_env("QT_QPA_PLATFORM", "wayland;xcb")
set_env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
set_env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
set_env("QT_QPA_PLATFORMTHEME", "kde")
set_env("QT_QUICK_CONTROLS_STYLE", "org.kde.desktop")
set_env("KDE_COLOR_SCHEME", "FluxDots")
set_env("PLASMA_THEME", "breeze-dark")
set_env("QT_STYLE_OVERRIDE", "kvantum")
