-- Autostart Applications (end4 architecture)
exec_once("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
exec_once("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
exec_once("quickshell -n -p " .. HOME .. "/.config/quickshell/shell.qml")
exec_once("hyprpaper")
exec_once("wallust run " .. HOME .. "/.config/hypr/wallpapers/default.png")
exec_once("dunst")
exec_once("wl-paste --type text --watch cliphist store")
exec_once("wl-paste --type image --watch cliphist store")
exec_once("hypridle")
