#!/bin/bash
# Sync quickshell colors to Mako and Vicinae
# Called automatically by shell.qml whenever theme/colors change.
# Uses a lockfile + atomic writes to prevent corruption on rapid calls.

# Arguments:
# $1 = background hex     $7  = yellow hex
# $2 = surface hex        $8  = blue hex
# $3 = foreground hex     $9  = cyan hex
# $4 = accent hex         $10 = magenta hex
# $5 = red hex            $11 = textMuted hex
# $6 = green hex          $12 = themeName

BG="$1";   SUR="$2";  FG="$3";   ACC="$4"
RED="$5";  GRN="$6";  YEL="$7";  BLU="$8"
CYN="$9";  MAG="${10}"; MUT="${11}"; THEME="${12}"

# Fallback defaults if args are missing
[ -z "$BG"  ] && BG="#0d0f18";    [ -z "$SUR" ] && SUR="#1e1e2e"
[ -z "$FG"  ] && FG="#c0caf5";    [ -z "$ACC" ] && ACC="#7aa2f7"
[ -z "$RED" ] && RED="#f7768e";   [ -z "$GRN" ] && GRN="#9ece6a"
[ -z "$YEL" ] && YEL="#e0af68";   [ -z "$BLU" ] && BLU="#7aa2f7"
[ -z "$CYN" ] && CYN="#7dcfff";   [ -z "$MAG" ] && MAG="#bb9af7"
[ -z "$MUT" ] && MUT="#6D8895"

# Prevent parallel runs stomping on each other
LOCK="/tmp/qs-theme-sync.lock"
exec 9>"$LOCK"
flock -x 9

# Strip '#' for mako background-color opacity suffix
BG_HEX="${BG#\#}"

# ──────────────────────────────────────────────────────────────────────────
# 1. Update Mako Configuration (atomic write via temp file)
# ──────────────────────────────────────────────────────────────────────────
MAKO_CONF="$HOME/.config/mako/config"
MAKO_TMP="$(mktemp)"

cat <<EOF > "$MAKO_TMP"
# Take a look at the mako manpage with the command:
#   man 5 mako
# To view all configuration options.
# Automatically generated by quickshell theme sync — do not hand-edit.

font=JetBrains Mono Nerd Font 11
format=<b>%a ⏵</b> %s\n%b
sort=-time
layer=overlay
anchor=top-center
width=500
height=50
margin=5
padding=8,12,12
border-size=2
icons=1
max-icon-size=20
default-timeout=5000
ignore-timeout=1

# System Colors (synced from theme: $THEME)
background-color=#${BG_HEX}dd
text-color=$FG
border-color=$ACC
border-radius=12

[urgency=normal]
border-color=$ACC

[urgency=high]
border-color=$RED
default-timeout=0

[app-name=lightcord]
border-color=$MUT

[summary~="log-.*"]
border-color=$SUR
EOF

mv -f "$MAKO_TMP" "$MAKO_CONF"
makoctl reload 2>/dev/null

# ──────────────────────────────────────────────────────────────────────────
# 2. Update Vicinae Theme (atomic write via temp file)
# ──────────────────────────────────────────────────────────────────────────
VICINAE_THEME_DIR="$HOME/.local/share/vicinae/themes"
mkdir -p "$VICINAE_THEME_DIR"
VICINAE_TMP="$(mktemp)"

cat <<EOF > "$VICINAE_TMP"
# Automatically generated by quickshell theme sync — do not hand-edit.
[meta]
name = "Custom theme"
description = "Synchronized with quickshell theme: $THEME"
variant = "dark"
inherits = "vicinae-dark"

[colors.core]
accent             = "$ACC"
accent_foreground  = "$BG"
background         = "$BG"
foreground         = "$FG"
secondary_background = "$SUR"
border             = "$SUR"

[colors.main_window]
border = "$SUR"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "$SUR"

[colors.accents]
blue    = "$BLU"
green   = "$GRN"
magenta = "$MAG"
orange  = "$YEL"
red     = "$RED"
yellow  = "$YEL"
cyan    = "$CYN"
purple  = "$MAG"

[colors.shortcut]
border = "$SUR"
EOF

mv -f "$VICINAE_TMP" "$VICINAE_THEME_DIR/custom.toml"
vicinae theme set custom 2>/dev/null

# ──────────────────────────────────────────────────────────────────────────
# 3. Update Neovim Theme & Live Reload Active Neovim Instances
# ──────────────────────────────────────────────────────────────────────────
NVIM_THEME_DIR="$HOME/dotfiles/config/nvim/lua/generated"
mkdir -p "$NVIM_THEME_DIR"
NVIM_TMP="$(mktemp)"

# Detect light/dark mode from cache flag
IS_LIGHT=false
if [ -f "$HOME/.cache/quickshell/is_light_mode" ] && [ "$(cat "$HOME/.cache/quickshell/is_light_mode" 2>/dev/null)" = "true" ]; then
    IS_LIGHT=true
fi

python3 -c "
import os, colorsys

is_light = '$IS_LIGHT' == 'true'
bg = '$BG'
fg = '$FG'
acc = '$ACC'
red = '$RED'
grn = '$GRN'
yel = '$YEL'
blu = '$BLU'
cyn = '$CYN'
mag = '$MAG'
mut = '$MUT'

def hex_to_rgb(h):
    s = h.lstrip('#')
    if len(s) != 6: return (0,0,0)
    return int(s[0:2],16)/255, int(s[2:4],16)/255, int(s[4:6],16)/255

def luma(h):
    r, g, b = hex_to_rgb(h)
    def lin(c): return c/12.92 if c <= 0.04045 else ((c+0.055)/1.055)**2.4
    return 0.2126*lin(r) + 0.7152*lin(g) + 0.0722*lin(b)

def contrast_ratio(a, b_col):
    la, lb = luma(a)+0.05, luma(b_col)+0.05
    return max(la, lb) / min(la, lb)

def ensure_contrast(hex_col, bg_col, min_ratio=4.5):
    r, g, b = hex_to_rgb(hex_col)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    is_bg_light = luma(bg_col) > 0.50
    curr_col = hex_col
    step = -0.04 if is_bg_light else 0.04
    for _ in range(25):
        if contrast_ratio(curr_col, bg_col) >= min_ratio:
            break
        l = max(0.05, min(0.95, l + step))
        r_new, g_new, b_new = colorsys.hls_to_rgb(h, l, s)
        curr_col = '#{:02X}{:02X}{:02X}'.format(int(r_new*255), int(g_new*255), int(b_new*255))
    return curr_col

if is_light:
    bg_out   = bg if luma(bg) >= 0.85 else '#f8fafc'
    fg_out   = '#0f172a'
    sur_out  = '#e2e8f0'
    comment  = ensure_contrast(mut if mut != bg else '#57606a', bg_out, 4.5)
    keyword  = ensure_contrast(yel, bg_out, 4.5)
    func     = ensure_contrast(blu, bg_out, 4.5)
    string   = ensure_contrast(grn, bg_out, 4.5)
    type_col = ensure_contrast(cyn, bg_out, 4.5)
    ret_col  = ensure_contrast(mag, bg_out, 4.5)
    param    = ensure_contrast(red, bg_out, 4.5)
    acc_out  = ensure_contrast(acc, bg_out, 4.5)
    error    = ensure_contrast(red, bg_out, 4.5)
else:
    bg_out   = bg
    fg_out   = '#f8fafc'
    sur_out  = '#282c37'
    comment  = ensure_contrast(mut if mut != bg else '#8b949e', bg_out, 4.5)
    keyword  = ensure_contrast(yel, bg_out, 4.5)
    func     = ensure_contrast(blu, bg_out, 4.5)
    string   = ensure_contrast(grn, bg_out, 4.5)
    type_col = ensure_contrast(cyn, bg_out, 4.5)
    ret_col  = ensure_contrast(mag, bg_out, 4.5)
    param    = ensure_contrast(red, bg_out, 4.5)
    acc_out  = ensure_contrast(acc, bg_out, 4.5)
    error    = ensure_contrast(red, bg_out, 4.5)

theme_content = f'''-- Automatically generated by quickshell theme sync for theme: $THEME
return {{
    base00 = \"{bg_out}\",
    base01 = \"{bg_out}\",
    base02 = \"{sur_out}\",
    base03 = \"{comment}\",
    base04 = \"{fg_out}\",
    base05 = \"{fg_out}\",
    base06 = \"{keyword}\",
    base07 = \"{fg_out}\",
    base08 = \"{param}\",
    base09 = \"{ret_col}\",
    base0A = \"{keyword}\",
    base0B = \"{acc_out}\",
    base0C = \"{type_col}\",
    base0D = \"{func}\",
    base0E = \"{ret_col}\",
    base0F = \"{error}\",

    bg             = \"{bg_out}\",
    fg             = \"{fg_out}\",
    error          = \"{error}\",
    keyword        = \"{keyword}\",
    keyword_return = \"{ret_col}\",
    func           = \"{func}\",
    string         = \"{string}\",
    number         = \"{keyword}\",
    type           = \"{type_col}\",
    comment        = \"{comment}\",
    parameter      = \"{param}\",
    property       = \"{type_col}\",
    operator       = \"{fg_out}\",
    bracket        = \"{fg_out}\",
    builtin        = \"{keyword}\",
}}
'''

with open('$NVIM_TMP', 'w') as f:
    f.write(theme_content)
"

mv -f "$NVIM_TMP" "$NVIM_THEME_DIR/theme.lua"

# Live-reload all running Neovim instances over RPC sockets
for socket in /tmp/nvim*/* /run/user/1000/nvim*/*; do
    if [ -S "$socket" ]; then
        nvim --server "$socket" --remote-send "<Cmd>lua require('theme').reload()<CR>" 2>/dev/null &
    fi
done

# ──────────────────────────────────────────────────────────────────────────
# 4. Update KDE Color Scheme & Apply to Plasma / Qt / KDE Apps
# ──────────────────────────────────────────────────────────────────────────
KDE_SCHEME_DIR="$HOME/.local/share/color-schemes"
mkdir -p "$KDE_SCHEME_DIR"

hex_to_rgb() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "$r,$g,$b"
}

BG_RGB=$(hex_to_rgb "$BG")
SUR_RGB=$(hex_to_rgb "$SUR")
FG_RGB=$(hex_to_rgb "$FG")
ACC_RGB=$(hex_to_rgb "$ACC")

# Detect light/dark mode from cache flag
IS_LIGHT=false
if [ -f "$HOME/.cache/quickshell/is_light_mode" ] && [ "$(cat "$HOME/.cache/quickshell/is_light_mode")" = "true" ]; then
    IS_LIGHT=true
fi

# ──────────────────────────────────────────────────────────────────────────
# 4. GTK & Qt/KDE Themes (FIRST)
# ──────────────────────────────────────────────────────────────────────────
if [ "$IS_LIGHT" = "true" ]; then
    GTK_THEME="Breeze"
    PREFER_DARK="false"
    GSETTINGS_SCHEME="prefer-light"
    KDE_LOOKANDFEEL="org.kde.breeze.desktop"
    ICON_SUFFIX="-light"
    INACT_RGB=$(hex_to_rgb "#475569")
else
    GTK_THEME="Breeze-Dark"
    PREFER_DARK="true"
    GSETTINGS_SCHEME="prefer-dark"
    KDE_LOOKANDFEEL="org.kde.breezedark.desktop"
    ICON_SUFFIX="-dark"
    INACT_RGB="220,225,245"
fi

# GTK 3 & 4 Theme (first)
if [ -f "$HOME/.config/gtk-3.0/settings.ini" ]; then
    sed -i \
        -e "s/gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=$PREFER_DARK/" \
        -e "s/gtk-theme-name=.*/gtk-theme-name=$GTK_THEME/" \
        "$HOME/.config/gtk-3.0/settings.ini" 2>/dev/null || true
fi

if [ -f "$HOME/.config/gtk-4.0/settings.ini" ]; then
    sed -i \
        -e "s/gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=$PREFER_DARK/" \
        -e "s/gtk-theme-name=.*/gtk-theme-name=$GTK_THEME/" \
        "$HOME/.config/gtk-4.0/settings.ini" 2>/dev/null || true
fi

# XDG / gsettings color-scheme & gtk-theme (first)
gsettings set org.gnome.desktop.interface color-scheme "$GSETTINGS_SCHEME" 2>/dev/null || true
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"           2>/dev/null || true

# KDE full look-and-feel (first)
plasma-apply-lookandfeel --apply "$KDE_LOOKANDFEEL" 2>/dev/null || true

# KDE Color Scheme (FluxDots)
KDE_TMP="$(mktemp)"
cat <<EOF > "$KDE_TMP"
[General]
ColorScheme=FluxDots
Name=FluxDots
accentColor=$ACC_RGB
LastUsedCustomAccentColor=$ACC_RGB

[UiSettings]
ColorScheme=FluxDots

[KDE]
LookAndFeelPackage=$KDE_LOOKANDFEEL
contrast=7

[Colors:Window]
BackgroundNormal=$BG_RGB
ForegroundNormal=$FG_RGB
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[Colors:View]
BackgroundNormal=$BG_RGB
ForegroundNormal=$FG_RGB
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[Colors:Button]
BackgroundNormal=$SUR_RGB
ForegroundNormal=$FG_RGB
BackgroundAlternate=$BG_RGB
ForegroundInactive=$INACT_RGB

[Colors:Selection]
BackgroundNormal=$ACC_RGB
ForegroundNormal=255,255,255
BackgroundAlternate=$ACC_RGB
ForegroundInactive=255,255,255

[Colors:Header]
BackgroundNormal=$BG_RGB
ForegroundNormal=$FG_RGB

[Colors:Tooltip]
BackgroundNormal=$SUR_RGB
ForegroundNormal=$FG_RGB

[Colors:Complementary]
BackgroundNormal=$BG_RGB
ForegroundNormal=$FG_RGB
BackgroundAlternate=$SUR_RGB
ForegroundInactive=$INACT_RGB
ForegroundActive=$ACC_RGB

[WM]
activeBackground=$BG_RGB
activeBlend=$BG_RGB
activeForeground=$FG_RGB
inactiveBackground=$BG_RGB
inactiveBlend=$BG_RGB
inactiveForeground=$INACT_RGB
EOF

mv -f "$KDE_TMP" "$KDE_SCHEME_DIR/FluxDots.colors"
cp -f "$KDE_SCHEME_DIR/FluxDots.colors" "$HOME/.config/kdeglobals"
kwriteconfig6 --file kdeglobals --group General --key ColorScheme "Dummy" 2>/dev/null
plasma-apply-colorscheme FluxDots 2>/dev/null || true
kwriteconfig6 --file dolphinrc --group UiSettings --key ColorScheme "FluxDots" 2>/dev/null

if [ "$IS_LIGHT" = "true" ]; then
    kwriteconfig6 --file plasmarc --group Theme --key name breeze 2>/dev/null
else
    kwriteconfig6 --file plasmarc --group Theme --key name breeze-dark 2>/dev/null
fi

# ──────────────────────────────────────────────────────────────────────────
# 5. Icon Theme Switcher — Dynamic Tela Icons (SECOND)
# ──────────────────────────────────────────────────────────────────────────
ICON_THEME=$(python3 -c "
import os
from PIL import Image

wp_path = os.path.expanduser('~/.cache/wallust/current_wallpaper')
if not wp_path or not os.path.isfile(wp_path):
    wp_path = os.path.expanduser('~/.cache/quickshell/current_wallpaper')
is_light_wp = '$IS_LIGHT' == 'true'

best_base = 'Tela-blue'

if wp_path and os.path.isfile(wp_path):
    try:
        im = Image.open(wp_path).convert('RGB')
        im_small = im.resize((150, 150))
        colors = im_small.getcolors(30000)
        
        pixels = list(im_small.getdata())
        avg_luma = sum(0.299*r + 0.587*g + 0.114*b for r, g, b in pixels) / (len(pixels) * 255.0)
        if avg_luma > 0.50:
            is_light_wp = True
            with open(os.path.expanduser('~/.cache/quickshell/is_light_mode'), 'w') as f:
                f.write('true')
        else:
            with open(os.path.expanduser('~/.cache/quickshell/is_light_mode'), 'w') as f:
                f.write('false')

        if colors:
            hue_scores = {
                'Tela-pink': 0.0,
                'Tela-red': 0.0,
                'Tela-orange': 0.0,
                'Tela-ubuntu': 0.0,
                'Tela-yellow': 0.0,
                'Tela-green': 0.0,
                'Tela-manjaro': 0.0,
                'Tela-blue': 0.0,
                'Tela-nord': 0.0,
                'Tela-purple': 0.0,
                'Tela-dracula': 0.0,
                'Tela-black': 0.0,
                'Tela-grey': 0.0
            }
            
            for count, (r, g, b) in colors:
                h, s, v = colorsys.rgb_to_hsv(r/255.0, g/255.0, b/255.0)
                luma = 0.299*(r/255.0) + 0.587*(g/255.0) + 0.114*(b/255.0)
                if s >= 0.12 and 0.10 <= luma <= 0.90:
                    deg = h * 360.0
                    weight = count * (s ** 2)
                    if deg >= 335 or deg < 10:
                        hue_scores['Tela-pink'] += weight * 1.3
                        hue_scores['Tela-red'] += weight
                    elif 10 <= deg < 25:
                        hue_scores['Tela-red'] += weight * 1.3
                    elif 25 <= deg < 48:
                        hue_scores['Tela-orange'] += weight * 1.3
                        hue_scores['Tela-ubuntu'] += weight
                    elif 48 <= deg < 70:
                        hue_scores['Tela-yellow'] += weight * 1.2
                    elif 70 <= deg < 165:
                        hue_scores['Tela-green'] += weight * 1.2
                        hue_scores['Tela-manjaro'] += weight
                    elif 165 <= deg < 255:
                        hue_scores['Tela-blue'] += weight * 1.2
                        hue_scores['Tela-nord'] += weight
                        hue_scores['Tela-grey'] += weight * 0.5
                    elif 255 <= deg < 335:
                        hue_scores['Tela-purple'] += weight * 1.2
                        hue_scores['Tela-dracula'] += weight
            
            top_hue = max(hue_scores.items(), key=lambda x: x[1])
            if top_hue[1] > 1.0:
                best_base = top_hue[0]
    except Exception:
        pass

suffix = '-light' if is_light_wp else '-dark'
candidate = f'{best_base}{suffix}'
icon_dirs = [os.path.expanduser(f'~/.local/share/icons/{candidate}'), f'/usr/share/icons/{candidate}']
if any(os.path.isdir(d) for d in icon_dirs):
    print(candidate)
else:
    print(best_base)
")

# Apply Icon Theme (second)
[ -f "$HOME/.config/gtk-3.0/settings.ini" ] && sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-3.0/settings.ini" 2>/dev/null || true
[ -f "$HOME/.config/gtk-4.0/settings.ini" ] && sed -i "s/gtk-icon-theme-name=.*/gtk-icon-theme-name=$ICON_THEME/" "$HOME/.config/gtk-4.0/settings.ini" 2>/dev/null || true
gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME" 2>/dev/null || true
kwriteconfig6 --file kdeglobals --group Icons --key Theme "$ICON_THEME" 2>/dev/null



# ──────────────────────────────────────────────────────────────────────────
# 5. Update Kvantum Theme (FluxDots) for Wallust & Static Theme Modes
# ──────────────────────────────────────────────────────────────────────────
KVANTUM_DIR="$HOME/.config/Kvantum/FluxDots"
mkdir -p "$KVANTUM_DIR"

cat <<EOF > "$HOME/.config/Kvantum/kvantum.kvconfig"
[General]
theme=FluxDots
EOF

KV_TMP="$(mktemp)"
cat <<EOF > "$KV_TMP"
[General]
author=FluxDots
comment="Dynamic Kvantum theme for Wallust & Quickshell static themes ($THEME)"

[Applications]
Default=FluxDots

[GeneralColors]
window.color=$BG
window.text.color=$FG
base.color=$SUR
alt.base.color=$SUR
text.color=$FG
highlight.color=$ACC
highlight.text.color=#FFFFFF
button.color=$SUR
button.text.color=$FG
tooltip.color=$SUR
tooltip.text.color=$FG
inactive.window.color=$BG
inactive.text.color=$FG
EOF

mv -f "$KV_TMP" "$KVANTUM_DIR/FluxDots.kvconfig"



