# kitty.conf.template for Wallust v3

background   #322E37
foreground   #DBF0FC
cursor       #C796AC

selection_background #2b2d3a
selection_foreground #ffffff

color0  #56525C
color1  #362756
color2  #B43C5D
color3  #2174BD
color4  #FF7D5C
color5  #F8C063
color6  #97D3F6
color7  #C2E1F2
color8  #889DA9
color9  #362756
color10 #B43C5D
color11 #2174BD
color12 #FF7D5C
color13 #F8C063
color14 #97D3F6
color15 #C2E1F2
