$wallpaper = /home/tarzo/wallpaper/09evvxczlyqe1.png
$background = rgba(2C2725FF)
$foreground = rgba(ECFCAFFF)
$color0 = rgba(524C4AFF)
$color1 = rgba(387853FF)
$color2 = rgba(917458FF)
$color3 = rgba(79BEE5FF)
$color4 = rgba(79CAA0FF)
$color5 = rgba(F9DDB9FF)
$color6 = rgba(C9F51BFF)
$color7 = rgba(DBF284FF)
$color8 = rgba(9AA95DFF)
$color9 = rgba(387853FF)
$color10 = rgba(917458FF)
$color11 = rgba(79BEE5FF)
$color12 = rgba(79CAA0FF)
$color13 = rgba(F9DDB9FF)
$color14 = rgba(C9F51BFF)
$color15 = rgba(DBF284FF)
