return {
  bg             = "{{background}}",
  fg             = "{{foreground}}",
  error          = "{{color9}}",
  keyword        = "{{color3}}",
  keyword_return = "{{color10}}",
  func           = "{{color12}}",
  string         = "{{color10}}",
  number         = "{{color11}}",
  type           = "{{color14}}",
  comment        = "{{color5}}",
  parameter      = "{{color9}}",
  property       = "{{color6}}",
  operator       = "{{color15}}",
  bracket        = "{{color7}}",
  builtin        = "{{color3}}",
}
