// WallustColors.qml - Re-exports the WallustColors singleton
// The actual colors are generated by wallust-colors.qml in the parent directory
pragma Singleton

import QtQuick
import ".."

QtObject {
    // Re-export all properties from wallust-colors.qml
    readonly property string background: Wallust.background
    readonly property string foreground: Wallust.foreground
    readonly property string color0: Wallust.color0
    readonly property string color1: Wallust.color1
    readonly property string color2: Wallust.color2
    readonly property string color3: Wallust.color3
    readonly property string color4: Wallust.color4
    readonly property string color5: Wallust.color5
    readonly property string color6: Wallust.color6
    readonly property string color7: Wallust.color7
    readonly property string color8: Wallust.color8
    readonly property string color9: Wallust.color9
    readonly property string color10: Wallust.color10
    readonly property string color11: Wallust.color11
    readonly property string color12: Wallust.color12
    readonly property string color13: Wallust.color13
    readonly property string color14: Wallust.color14
    readonly property string color15: Wallust.color15
    
    // Semantic aliases
    readonly property string accent: Wallust.accent
    readonly property string surface: Wallust.surface
    readonly property string textMuted: Wallust.textMuted

    // Dynamic color mappings matching theme palettes
    readonly property string black: Wallust.color0
    readonly property string red: Wallust.color1
    readonly property string green: Wallust.color2
    readonly property string yellow: Wallust.color3
    readonly property string blue: Wallust.color4
    readonly property string magenta: Wallust.color5
    readonly property string cyan: Wallust.color6
    readonly property string white: Wallust.color7

    // Additional colors mapped dynamically
    readonly property string lime: Wallust.color14
    readonly property string amber: Wallust.color11
    readonly property string indigo: Wallust.color12
    readonly property string grey: Wallust.color8
}